info:
  version: @project.version@
server:
  port: 6060
  context-path: /uaa
spring:
  application:
    name: auth
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
security:
#  basic:
#    enabled: false
  user:
    password: password
