CREATE TABLE "USERS"(
  "USERNAME" VARCHAR2(100) PRIMARY KEY,
  "NAME" VARCHAR2(255) NOT NULL,
  "PASSWORD" VARCHAR2(100) NOT NULL,
  "EXPIRED" VARCHAR2(1) NOT NULL,
  "LOCKED" VARCHAR2(1) NOT NULL,
  "ENABLED" VARCHAR2(1) NOT NULL,
  "PASSWORD_CHANGE_DATE" DATETIME
);

CREATE TABLE "SCOPES"(
  "USERNAME" VARCHAR2(100) NOT NULL,
  "AUTHORITY" VARCHAR2(50) NOT NULL
);

CREATE TABLE "CLIENTS"(
  "CLIENT_ID" VARCHAR2(100) PRIMARY KEY,
  "CLIENT_SECRET" VARCHAR2(100) NOT NULL,
  "USERNAME" VARCHAR2(100) NOT NULL,
  "SECRET_REQUIRED" VARCHAR2(1) NOT NULL,
  "GRANT_TYPES" VARCHAR2(100) NOT NULL,
  "REDIRECT_URI" VARCHAR2(2000) NOT NULL,
  "ACCESS_VALIDITY_SECOND" INTEGER,
  "REFRESH_VALIDITY_SECOND" INTEGER
);